name: care_share_nepal
description: A Flutter application for Care Share Nepal.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  intl: ^0.19.0
  dartz: ^0.10.1
  dio: ^5.4.0
  shared_preferences: ^2.2.3
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.17
  freezed_annotation: ^2.4.1
  freezed: ^2.3.5
  formz: ^0.8.0
  get_it: ^8.0.3
  google_nav_bar: ^5.0.7
  fluttertoast: ^8.2.10
  dotted_border: ^2.1.0
  fresh_dio: ^0.4.1
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  esewa_flutter_sdk:
    path: ./esewa_flutter_sdk
    

dev_dependencies:
  bloc_test: ^9.1.7 
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  freezed: ^2.3.5
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/images/items/
    - assets/images/clothes/
  fonts:
    - family: PublicSans
      fonts:
        - asset: fonts/PublicSans.ttf
    - family: LeagueSpartanRegular
      fonts:
        - asset: fonts/LeagueSpartan-Regular.ttf
  
